title: "The Illustrated GRPO: A Detailed and Pedagogical Explanation of Group Relative Policy Optimization (GRPO) Algorithm"
description: "A thorough, pedagogical, and comprehensive guide to the GRPO algorithm for fine-tuning LLMs to enhance their reasoning abilities. Ideal for those seeking an in-depth understanding of the GRPO Algorithm, its logic, the maths behind it, its implementation, and a practical guide to perform GRPO fine-tuning."
header_pages: false  # Optional: prevents header generation if present
baseurl: /the-illustrated-grpo
url: https://abderrahmanskiredj.github.io/the-illustrated-grpo
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: Abderrahman Skiredj
  email: abderrahman.skiredj@um6p.ma
social:
  links:
    - https://www.linkedin.com/in/abderrahman-skiredj-99a80510b/
    - https://huggingface.co/AbderrahmanSkiredj1
    - https://scholar.google.com/citations?user=oUFfQTIAAAAJ
markdown: kramdown  # Markdown processor that supports MathJax
kramdown:
  math_engine: mathjax  # Tells kramdown to expect MathJax for LaTeX
  input: GFM  # GitHub Flavored Markdown, matches GitHub’s rendering
